# Generated by Django 4.2.3 on 2023-08-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время рассылки'),
        ),
    ]
