# Generated by Django 4.2.3 on 2023-08-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailingsettings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='time',
            field=models.TimeField(verbose_name='Время рассылки'),
        ),
    ]
