# Generated by Django 4.2.3 on 2023-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingsettings_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='time',
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время старта'),
        ),
    ]
