# Generated by Django 4.2.3 on 2023-08-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_remove_mailingsettings_time_mailingsettings_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время старта'),
        ),
    ]
