# Generated by Django 4.2.3 on 2023-08-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailingsettings_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='last_try',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время последней попытки'),
        ),
    ]
