# Generated by Django 4.2.3 on 2023-08-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_customer_owner_mailingsettings_owner_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ сервера'),
        ),
    ]
