# Generated by Django 4.2.3 on 2023-08-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_mailinglog_server_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'ordering': ('start_time',), 'permissions': [('set_status', 'Can change status')], 'verbose_name': 'Paccылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
