# Generated by Django 4.2.3 on 2023-08-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
